---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(ggthemes)
library(rstatix)
library(ggpubr)
```

# Q2 and Q3
```{r}
assignment5 = read_csv("assignment5_data.csv")

subject_accuracy = assignment5%>%
  group_by(subject, prime_condition)%>%
  summarize(mean_acc = mean(accuracy))
  

subject_rt = assignment5 %>%
  group_by(subject, prime_condition)%>%
  summarize(mean_rt = mean(response_RT))

#Q3: Both are in long format.
```
#Q4
```{r}
subject_accuracy_wide = subject_accuracy%>%
  pivot_wider(names_from = prime_condition, values_from = mean_acc)
```
#Q5 and Q6
```{r}
subject_accuracy_long = subject_accuracy_wide%>%
  pivot_longer(names_to = "prime_condition", cols = both:unrelated)

#Q6: subject_accuracy
```
#Q7 and Q8
```{r}
#7a:subject_accuracy_wide
#7b:paired

t.test(subject_accuracy_wide$phonological, subject_accuracy_wide$semantic, var.equal = FALSE, paired = TRUE)

#Q8:Because the t-value is 4.4075, it is significant.
```
#9
```{r}
#t-value

subject_accuracy_wide = subject_accuracy_wide%>%
  mutate(diff=phonological - semantic)

x_bar=mean(subject_accuracy_wide$diff)
sd_diff=sd(subject_accuracy_wide$diff)

t=x_bar/(sd_diff/sqrt(nrow(subject_accuracy_wide)))

#p-value

df= nrow(subject_accuracy_wide)-1

p_value=2*(1-pt(t,df))
```
#10
```{r}
subject_accuracy_wide=subject_accuracy_wide%>% ungroup()

hist(subject_accuracy_wide$diff)

outliers = subject_accuracy_wide %>% identify_outliers(diff)

#Only one outlier was found, 97.

outliers_subs= outliers%>% pull(subject)
newdf= subject_accuracy_wide%>%filter(!subject %in% outliers_subs)
```
#11
```{r}
ggqqplot(subject_accuracy_wide, "diff")
subject_accuracy_wide%>%shapiro_test(diff)
#Yes, the p-value is greater than 0.05
```
#12

```{r}
mean_accuracy=assignment5%>%
  group_by(prime_condition)%>%
  summarize(mean_acc = mean(accuracy))

mean_accuracy%>%
  ggplot(aes(x=prime_condition, y=mean_acc))+
  geom_bar(stat = "identity")+
  theme_fivethirtyeight()
#It seems like phonological improves accuracy while semantic hurts it.
```
#13
```{r}
mean_rt= assignment5%>%
  group_by(prime_condition)%>%
  summarise(mean_rt= mean(response_RT))

mean_rt%>%
  ggplot(aes(x=prime_condition, y=mean_rt))+
  geom_bar(stat = "identity")+
  theme_fivethirtyeight()+
  xlab("Prime Condidition") + 
  ylab ("Mean RT")+
  ggtitle("Reaction Time vs Prime Condition")

#Q13:On average, they look relatively the same to one another. The prime condition with both produced the fastest reaction time while the semantic prime condition produced the slowest reaction time.
```
#14
```{r}
#14a Wide conversion
subject_rt_wide=subject_rt%>%
  pivot_wider(names_from = prime_condition, values_from = mean_rt)
```

```{r}
#14b Outliers 
subject_rt_wide=subject_rt_wide%>%
  mutate(diff2=both-semantic)

subject_rt_wide=subject_rt_wide%>% ungroup()

outliers2= subject_rt_wide%>%identify_outliers(diff2)
#no outliers

```

```{r}
#14c Normality
subject_rt_wide%>%shapiro_test(diff2)
#p-value>0.05 
```

```{r}
#14d T-test
t.test(subject_rt_wide$both, subject_rt_wide$semantic, var.equal = FALSE, paired = TRUE)
```
#15
```{r}
assignment5%>%
  ggplot(aes(x=distance, y=response_RT, color = prime_condition))+
  geom_smooth(method = "lm")
```

